server:
  port: ${PORT:8080}
logging:
  level:
    org:
      atmosphere: warn

spring:
  mustache:
    check-template-location: false

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: 27017
      database: oauth2
      username: admin
      password: secret123
      authentication-database: admin
      auto-index-creation: true
vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.shieldteq.auth
